version: '3.8'
services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:${ELASTIC_AGENT_VERSION}
    container_name: elastic-agent
    hostname: ${NODE_NAME}
    restart: unless-stopped
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    env_file: .env
    environment:
      - FLEET_ENROLLMENT_TOKEN=${FLEET_ENROLLMENT_TOKEN}
      - FLEET_ENROLL=1
      - FLEET_URL=${FLEET_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  elastic-filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_AGENT_VERSION}
    container_name: elastic-filebeat
    hostname: ${NODE_NAME}
    env_file: .env
    user: root
    restart: unless-stopped
    entrypoint: "filebeat -e -strict.perms=false"
    pid: "host" # access and manipulate other containers
    privileged: true
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
