filebeat.inputs:
- type: log
  id: my-filestream-id
  enabled: true
  # where to grab logs
  paths:
    - /var/lib/docker/containers/*/*.log
    - /var/log/*.log

# auth data
cloud.id: "${ELASTIC_CLOUD_ID}"
cloud.auth: "${ELASTIC_API_AUTH}"

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
