log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'
    http:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':443'

certificatesResolvers:
  letsencrypt:
    # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
    acme:
      # TODO: email from ENV
      email: 'phonxis@gmail.com'
      storage: /etc/traefik/acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

# TLS certificates definition
# https://doc.traefik.io/traefik/https/tls/

http:
  routers:
    web-secure-router:
      rule: 'Host(`<project_domain>`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://doc.traefik.io/traefik/routing/routers/#certresolver
        certResolver: letsencrypt

    web-media-router:
      rule: 'Host(`<project_domain>`) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

    web-static-router:
      rule: 'Host(`<project_domain>`) && PathPrefix(`/static/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-static
      tls:
        certResolver: letsencrypt

    # TODO: setup redash
    #redash-router:
    #  rule: 'Host(`redash.<project_domain>`)'
    #  entryPoints:
    #    - web-secure
    #  middlewares:
    #    - csrf
    #  service: redash
    #  tls:
    #    certResolver: letsencrypt

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5005

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

    django-static:
      loadBalancer:
        servers:
          - url: http://nginx:80

    # TODO: setup redash
    #redash:
    #  loadBalancer:
    #    servers:
    #      - url: http://redash_server:5000

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true